artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type: attribute
    prefix: /media
ux_media:
    resource: "@ArkounayUxMediaBundle/Controller"
    type:     attribute
    prefix:   /ux-media